[metadata]
name = 'Gruvbox Material Dark'

[colors]
background = '#32302f'
foreground = '#d4be98'
cursor_bg = '#928374'
cursor_fg = '#32302f'
cursor_border = '#928374'
compose_cursor = '#b47109'
# selection_fg = '#32302f'
# selection_bg = '#d4be98'
selection_bg = 'rgba(146, 131, 116, 0.25)'
split = '#504945'
ansi = [
  '#3c3836',
  '#c14a4a',
  '#6c782e',
  '#b47109',
  '#45707a',
  '#945e80',
  '#4c7a5d',
  '#928374',
]
brights = [
  '#665c54',
  '#ea6962',
  '#a9b665',
  '#d8a657',
  '#7daea3',
  '#d3869b',
  '#89b482',
  '#d4be98',
]

[colors.tab_bar]
background = 'rgba(50, 48, 47, 0)'

[colors.tab_bar.active_tab]
bg_color = 'rgba(50, 48, 47, 0)'
fg_color = '#665c54'

[colors.tab_bar.inactive_tab]
bg_color = 'rgba(50, 48, 47, 0)'
fg_color = '#504945'

[colors.tab_bar.inactive_tab_hover]
bg_color = 'rgba(50, 48, 47, 0)'
fg_color = '#928374'

[colors.tab_bar.new_tab]
bg_color = 'rgba(50, 48, 47, 0)'
fg_color = '#504945'

[colors.tab_bar.new_tab_hover]
bg_color = 'rgba(50, 48, 47, 0)'
fg_color = '#928374'

